### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by Ras0N** [GamemakerChina/gms2translation#11]
Release版本文本内容有翻译错误。

翻译错误位置可能在：ide_chinese.csv文件的第1699行。

Manual应该翻译为“**手动**”而不是“**帮助文档**”，这里的Manual应该为碰撞遮罩的设定，与帮助文档无关。

位于sprite的编辑界面。
翻译具体显示：
![210217](https://user-images.githubusercontent.com/25833974/108089088-2b6e3880-70b4-11eb-8eba-c7d8c0efad5f.jpg)

**Comment by LiarOnce** [comment]
感谢指正
