### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by tpxxn** [GamemakerChina/gms2translation#4]
Line 2651：android_fullinstall：始终安全安装 APK -> 始终完全安装 APK

**Comment by tpxxn** [comment]
G->Line

**Comment by tpxxn** [comment]
Line 3607/3609：GMStdTarget：目标列表 -> 目标变量
GMStdFreeTarget：释放目标列表 -> 释放目标变量

**Comment by deciia** [comment]
偏好  常观设置  省电管理  
文件观察频率（毫秒） 改为 文件监视频率（毫秒）

**Comment by deciia** [comment]
偏好 常规  工作区
Workspace keyboard navigation resets zoom
原译：工作区键盘导航会重置缩放
修改：？
